spring:
  datasource:
    url: jdbc:mysql://localhost:3306/p1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '12341234'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false